# Конфигурация сайта грузоперевозок
# Отредактируйте этот файл перед запуском

# SEO настройки
seo:
  title: "Грузоперевозки по России - Быстро, Надежно, Недорого"
  description: "Профессиональные грузоперевозки по Москве и России. Газели, фургоны, грузчики. Расчет стоимости онлайн. Работаем 24/7. Звоните: +7 (800) 555-77-77"
  keywords: "грузоперевозки, грузовое такси, газель, переезд, грузчики, доставка грузов"

# Основная информация
site:
  companyName: "ГрузЭкспресс"
  tagline: "Ваш надежный партнер в перевозках"
  phone: "+7 (800) 555-77-77"
  whatsapp: "+79001234567"
  email: "info@gruz-express.ru"
  address: "г. Москва, ул. Транспортная, д. 1"
  workingHours: "Круглосуточно, без выходных"
  inn: "7701234567"
  ogrn: "1234567890123"

# Hero секция
hero:
  title: "Грузоперевозки по Москве и России"
  subtitle: "Быстро, надежно, недорого. Рассчитайте стоимость за 30 секунд"
  buttonText: "Рассчитать стоимость"
  features:
    - "Работаем с 2010 года"
    - "Более 10 000 перевозок"
    - "Страхование грузов"
    - "Без скрытых платежей"

# Услуги
services:
  - id: 1
    name: "Газель"
    capacity: "1.5 тонны"
    volume: "9 м³"
    price: "от 800 ₽/час"
    dimensions: "3.0 x 1.8 x 1.8 м"
    description: "Идеально для переезда 1-2 комнатной квартиры, перевозки мебели"
    icon: "Truck"
    popular: true
    
  - id: 2
    name: "Газель удлиненная"
    capacity: "2 тонны"
    volume: "14 м³"
    price: "от 1000 ₽/час"
    dimensions: "4.2 x 1.8 x 1.8 м"
    description: "Оптимально для переезда 3-комнатной квартиры"
    icon: "Truck"
    popular: true
    
  - id: 3
    name: "Фургон 3 тонны"
    capacity: "3 тонны"
    volume: "20 м³"
    price: "от 1500 ₽/час"
    dimensions: "4.5 x 2.0 x 2.0 м"
    description: "Для крупных переездов и коммерческих грузов"
    icon: "Truck"
    popular: false
    
  - id: 4
    name: "Фургон 5 тонн"
    capacity: "5 тонн"
    volume: "32 м³"
    price: "от 2000 ₽/час"
    dimensions: "6.0 x 2.2 x 2.2 м"
    description: "Для офисных переездов и больших объемов"
    icon: "Truck"
    popular: false

# Дополнительные услуги
additionalServices:
  - name: "Грузчики"
    price: "500 ₽/час за человека"
    icon: "Users"
    description: "Профессиональная бригада"
    
  - name: "Упаковка"
    price: "от 50 ₽/коробка"
    icon: "Package"
    description: "Материалы и работа"
    
  - name: "Сборка/разборка мебели"
    price: "от 300 ₽"
    icon: "Wrench"
    description: "Опытные специалисты"
    
  - name: "Подъем на этаж"
    price: "от 200 ₽/этаж"
    icon: "ArrowUp"
    description: "Без лифта"

# Преимущества
benefits:
  - icon: "Clock"
    title: "Работаем 24/7"
    description: "Принимаем заказы круглосуточно, доступны в любое время"
    
  - icon: "Shield"
    title: "Страхование грузов"
    description: "Полная ответственность за сохранность вашего имущества"
    
  - icon: "Award"
    title: "Опытные водители"
    description: "Стаж работы от 5 лет, знание всех маршрутов"
    
  - icon: "Banknote"
    title: "Прозрачные цены"
    description: "Без скрытых доплат, стоимость фиксируется в договоре"
    
  - icon: "Star"
    title: "Высокий рейтинг"
    description: "4.9/5 на основе 1200+ отзывов наших клиентов"
    
  - icon: "Headphones"
    title: "Поддержка клиентов"
    description: "Диспетчерская служба на связи в любое время"

# Как мы работаем
howItWorks:
  - step: 1
    icon: "Phone"
    title: "Оставьте заявку"
    description: "Позвоните или заполните форму на сайте"
    
  - step: 2
    icon: "Calculator"
    title: "Расчет стоимости"
    description: "Менеджер рассчитает точную стоимость"
    
  - step: 3
    icon: "FileCheck"
    title: "Заключение договора"
    description: "Подписываем договор, фиксируем цену"
    
  - step: 4
    icon: "Truck"
    title: "Выполнение заказа"
    description: "Доставляем груз точно в срок"

# Цены (базовые тарифы)
pricing:
  withinMKAD:
    name: "В пределах МКАД"
    description: "Перевозки по Москве"
    gazelle: "800 ₽/час"
    gazelleXL: "1000 ₽/час"
    truck3t: "1500 ₽/час"
    truck5t: "2000 ₽/час"
    minTime: "Минимум 3 часа"
    
  outOfMKAD:
    name: "За МКАД"
    description: "По Московской области"
    basePrice: "Тариф МКАД + 35 ₽/км"
    minDistance: "Минимальный заказ 5000 ₽"
    
  intercity:
    name: "Межгород"
    description: "По России"
    calculation: "Индивидуальный расчет"
    discount: "Скидки при регулярных перевозках"

# FAQ
faq:
  - question: "Сколько стоит грузоперевозка по Москве?"
    answer: "Стоимость зависит от типа транспорта и времени работы. Газель - от 800 ₽/час, минимальный заказ 3 часа. Точную стоимость рассчитает наш менеджер после уточнения деталей."
    
  - question: "Как быстро вы можете подать машину?"
    answer: "В пределах МКАД - от 30 минут до 2 часов в зависимости от загруженности. Можно заказать машину заранее на удобное вам время."
    
  - question: "Нужны ли грузчики?"
    answer: "Грузчики - дополнительная опция. Стоимость 500 ₽/час за человека. Рекомендуем заказывать при перевозке мебели и тяжелых грузов."
    
  - question: "Вы работаете с юридическими лицами?"
    answer: "Да, работаем как с физическими, так и с юридическими лицами. Предоставляем полный пакет документов, работаем по безналу."
    
  - question: "Что входит в страхование груза?"
    answer: "Мы страхуем все перевозимые грузы. В случае повреждения или утери компенсируем ущерб согласно договору."
    
  - question: "Можно ли отменить или перенести заказ?"
    answer: "Да, вы можете отменить или перенести заказ не позднее чем за 2 часа до назначенного времени без штрафов."

# Отзывы
testimonials:
  - id: 1
    name: "Алексей М."
    rating: 5
    text: "Переезжали с женой в новую квартиру. Ребята молодцы, все быстро и аккуратно перевезли. Мебель собрали и расставили. Цена соответствует качеству."
    date: "15.03.2025"
    service: "Газель + грузчики"
    
  - id: 2
    name: "Мария К."
    rating: 5
    text: "Заказывала доставку дивана из магазина. Водитель приехал вовремя, помог занести на 5 этаж. Очень вежливый и аккуратный. Рекомендую!"
    date: "10.03.2025"
    service: "Газель"
    
  - id: 3
    name: "ООО 'Техника'"
    rating: 5
    text: "Сотрудничаем уже год. Перевозим оборудование по Москве и области. Всегда вовремя, без повреждений. Отличная компания для бизнеса."
    date: "05.03.2025"
    service: "Фургон 5 тонн"

# Контакты и социальные сети
contacts:
  phone: "+7 (800) 555-77-77"
  whatsapp: "+79001234567"
  telegram: "@gruzexpress"
  email: "info@gruz-express.ru"
  vk: "https://vk.com/gruzexpress"
  instagram: "https://instagram.com/gruzexpress"

# Футер
footer:
  copyright: "© 2025 ГрузЭкспресс. Все права защищены."
  links:
    - title: "О компании"
      url: "/about"
    - title: "Услуги"
      url: "#services"
    - title: "Цены"
      url: "#pricing"
    - title: "Контакты"
      url: "#contacts"
    - title: "Политика конфиденциальности"
      url: "/privacy"

# Настройки калькулятора
calculator:
  enabled: true
  defaultService: "gazelle"
  defaultHours: 3
  defaultLoaders: 0
  loadersPrice: 500
  
# Редактор (для владельца сайта)
editor:
  enabled: true
  password: "admin123"
  editableFields:
    - "hero.title"
    - "hero.subtitle"
    - "site.phone"
    - "site.whatsapp"
    - "services[].price"
    - "additionalServices[].price"
    - "testimonials"

# Цветовая схема
colors:
  primary: "#2563EB" # Синий
  secondary: "#F59E0B" # Оранжевый
  accent: "#10B981" # Зеленый
  background: "#F8FAFC" # Светлый
  text: "#1E293B" # Темно-серый
